config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :users, only: :create
  resources :ratings, only: [:create, :update]
  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  include Custom::Avg
  has_many :ratings

  scope :visit_order, -> { order(last_visited: :asc) }

  def avg_rating
    Custom::Avg.avg(ratings.map { |r| r.stars }.reject { |r| r == nil})
  end

  def days_since_visit
    return 5 unless last_visited
    (Date.today - last_visited).to_i
  end

  def self.recommendation
    restaurants = Restaurant.visit_order.where("last_visited <= ? OR last_visited IS NULL", 1.day.ago)
    restaurants = Restaurant.visit_order if restaurants.empty?
    ratings = final_ratings(restaurants)
    ratings.max { |a,b| a[1] <=> b[1] }[0]
  end

  private

  def self.final_ratings(restaurants)
    avg_ratings(restaurants).map { |r| [r[0], r[1] + r[0].days_since_visit] }
  end

  def self.avg_ratings(restaurants)
    avgs = restaurants.map { |r| [r, r.avg_rating] }
    avgs.map { |r| r[1] == nil ? [r[0], 3] : r } # convert nils to 3
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    @rating = Rating.find_or_initialize_by(rating_params)

    respond_to do |format|
      if @rating.save
        flash[:success] = 'Rating was successfully created.'
        format.html { redirect_to restaurants_path }
        format.json { render :index, status: :created }
      else
        flash[:danger] = 'There was a problem creating your rating.'
        format.html { redirect_to restaurants_path }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @rating = Rating.find_or_initialize_by(rating_params)
    @rating.stars = params[:rating][:stars]

    respond_to do |format|
      if @rating.update(rating_params)
        flash[:success] = 'Rating was successfully updated.'
        format.html { redirect_to restaurants_path }
        format.json { render :index, status: :ok }
        format.js
      else
        flash[:danger] = 'There was a problem updating your rating.'
        format.html { redirect_to restaurants_path }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:user_id, :restaurant_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
    @recommendation = Restaurant.recommendation
    set_user
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
    set_user
  end

  # GET /restaurants/1/edit
  def edit
    set_user
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        flash[:success] = 'Restaurant was successfully created.'
        format.html { redirect_to restaurants_path }
        format.json { render :index, status: :created }
      else
        flash[:danger] = 'There was a problem creating the restaurant.'
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        flash[:success] = 'Restaurant was successfully updated.'
        format.html { redirect_to restaurants_path }
        format.json { render :index, status: :ok }
      else
        flash[:danger] = 'There was a problem updating the restaurant.'
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      flash[:success] = 'Restaurant was successfully destroyed.'
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :last_visited)
  end

  def set_user
    if session[:current_user]
      @user = User.find_by(id: session[:current_user])
    else
      @user = User.new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.find_or_initialize_by(user_params)

    respond_to do |format|
      if @user.save
        session[:current_user] = @user.id
        flash[:success] = 'User was successfully created.'
        format.html { redirect_to restaurants_path }
        format.json { render :index, status: :created }
      else
        flash[:danger] = 'There was a problem creating the user.'
        format.html { redirect_to restaurants_path }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_flash.html.haml
.row
  .col-md-1
  .col-md-10
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-#{name}", id: 'flash'
  .col-md-1

app/views/layouts/_header.html.haml
.row{ style: "background: #4e638e; color: white;" }
  .col-md-4
    %h2 What's for Lunch?
  .col-md-3
  .col-md-5
    = render "users/user_bar"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatsForLunch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main-container" class="container">
      <%= render "layouts/header" %>
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.haml
= form_for @restaurant do |f|
  - if @restaurant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@restaurant.errors.count, "error")} prohibited this restaurant from being saved:"
      %ul
        - @restaurant.errors.full_messages.each do |msg|
          %li= msg

  .field.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  - if show_visited
    .field.form-group
      = f.label :last_visited
      = f.date_select :last_visited, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/restaurants/_log_visit.haml
= form_for restaurant do |f|
  = f.hidden_field :last_visited, value: Date.today
  = f.submit 'Log Visit', class: 'btn btn-default'

app/views/restaurants/_restaurant.html.haml
%tr
  %td
    = restaurant.name
  %td
    = restaurant.last_visited
  %td
    - avg = restaurant.avg_rating
    = avg.to_i if avg != nil
  %td
    - rating = restaurant.ratings.find_or_initialize_by(user_id: @user.id)
    .user_stars{ 'data-user_rat' => rating.stars, 'data-rat_id' => rating.id }
      = form_for rating do |f|
        = f.hidden_field :restaurant_id, value: restaurant.id
        = f.hidden_field :user_id, value: rating.user_id
        = f.number_field :stars, class: 'rating', 'data-size' => 'xs'
        = f.submit 'Submit', class: 'btn btn-primary btn-success'
  %td
    = render partial: 'log_visit', locals: { restaurant: restaurant }
  %td
    = link_to 'Edit', edit_restaurant_path(restaurant), class: 'btn btn-default'
  %td
    = link_to 'Destroy', restaurant, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/restaurants/edit.html.haml
%h1 Editing restaurant

= render partial: 'form', locals: { show_visited: true }

= link_to 'Back', restaurants_path, class: 'btn btn-default'

app/views/restaurants/index.html.haml
%h3
  = "Today's Lunch is: #{@recommendation.name}"
%hr
%h4 Restaurants
%table.table
  %thead
    %tr
      %th Name
      %th Last visited
      %th Avg Rating
      %th Your Rating
      %th
      %th
      %th

  %tbody
    - @restaurants.each do |restaurant|
      = render partial: 'restaurant', locals: { restaurant: restaurant }

%br
= link_to 'New Restaurant', new_restaurant_path, class: 'btn btn-default'

app/views/restaurants/new.html.haml
%h1 New restaurant

= render partial: 'form', locals: { show_visited: false }

= link_to 'Back', restaurants_path, class: 'btn btn-default'

app/views/users/_user_bar.html.haml
- if @user.username
  %h4{ style: "padding-top: 15px; padding-left: 100px;" }
    = "Hello #{@user.username}"
- else
  = form_for @user, html: { class: 'form-inline', style: "padding-top: 15px;" } do |f|
    .field.form-group
      = f.label :username
      = f.text_field :username, class: 'form-control'
    .actions.form-group{ style: "padding-left: 5px;" }
      = f.submit 'Login', class: 'btn btn-primary'
    .actions.form-group{ style: "padding-left: 5px;" }
      = f.submit 'New User', class: 'btn btn-primary'